database:
  host: "localhost"
  user: "postgres"
  dbname: "teaching-platform"
  port: 5432
password:
  length: 5
  uppercase: 1
  numbers: 2
  special: 1
  nonletters: 2
logging:
  logging_lvl: "INFO"